/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.raven.form;

//import com.lowagie.text.Cell;
import dao.HangHoaDAO;
import dao.KetNoi;
import dao.NhaCCDAO;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import pojo.HangHoa;
import pojo.NhaCungCap;



/**
 *
 * @author RAVEN
 */
public class Form_DanhMucHangHoa extends javax.swing.JPanel {

    
    String tieude[]={"Mã hàng", "Tên hàng hóa", "Đơn vị tính", "Giá bán","Số lượng","Mã nhóm hàng"};
    DefaultTableModel tbl_mode = new DefaultTableModel();
    /**
     * Creates new form Form_1
     */
    public Form_DanhMucHangHoa() {
        initComponents();
        DefaultTableModel tblModel;
        tblModel = (DefaultTableModel) this.tbl_danhsachHanghoa.getModel();
        tbl_mode.setColumnIdentifiers(tieude);
        tbl_danhsachHanghoa.setModel(tbl_mode);
        HienThi_DSHH();
        Load_CboTenLoaiHH();
        Load_CboTenLoaiHH_tiemKiem();        
        Load_CboDVT();
        txt_maHH.setEnabled(false);
        chinhFont();
        updateRowHeights();   
        txt_maNH.setVisible(false);
    }           
      public void chinhFont()
    {
        tbl_danhsachHanghoa.getTableHeader().setFont(new Font("SansSerif", Font.BOLD, 20)); // chỉnh font chữ lại cho title
        tbl_danhsachHanghoa.getTableHeader().setFont(new Font("SansSerif", Font.BOLD, 20));
    }
    private void updateRowHeights()
    {
        for (int row = 0; row < tbl_danhsachHanghoa.getRowCount(); row++)
        {
            int rowHeight = tbl_danhsachHanghoa.getRowHeight();

            for (int column = 0; column < tbl_danhsachHanghoa.getColumnCount(); column++)
            {
                Component comp = tbl_danhsachHanghoa.prepareRenderer(tbl_danhsachHanghoa.getCellRenderer(row, column), row, column);
                rowHeight = Math.max(rowHeight, comp.getPreferredSize().height);
            }

            tbl_danhsachHanghoa.setRowHeight(row, rowHeight);
        }
              
    }
   private void Load_CboTenLoaiHH()
   {
   
       ArrayList<String> dsTenNH= HangHoaDAO.layDSTenNH();
       DefaultComboBoxModel cbomode = (DefaultComboBoxModel) cbo_tenLoaiHH.getModel();
       cbo_tenLoaiHH.removeAllItems();
         
        for(int i=0; i<dsTenNH.size(); i++)
        {
             cbomode.addElement(dsTenNH.get(i));
        }
       
   }    
   private void Load_CboTenLoaiHH_tiemKiem()
   {
   
       ArrayList<String> dsTenNH= HangHoaDAO.layDSTenNH();
       DefaultComboBoxModel cbomode = (DefaultComboBoxModel) cbo_tenLoaiHH_TimKiem.getModel();
       cbo_tenLoaiHH_TimKiem.removeAllItems();
         
        for(int i=0; i<dsTenNH.size(); i++)
        {
             cbomode.addElement(dsTenNH.get(i));
        }
       
   }  
      private void Load_CboDVT()
   {
        
       ArrayList<String> dsDVT= HangHoaDAO.layDSDVT();
       DefaultComboBoxModel cbomode = (DefaultComboBoxModel) cbo_dvt.getModel();
       cbo_dvt.removeAllItems();
         
        for(int i=0; i<dsDVT.size(); i++)
        {
             cbomode.addElement(dsDVT.get(i));
        }   
   }    
   
   private void HienThi_DSHH() {
        ArrayList<HangHoa> dsNCC = HangHoaDAO.layDSHangHoa();
        DefaultTableModel dtb = (DefaultTableModel)tbl_danhsachHanghoa.getModel();
        dtb.setRowCount(0);
        for(HangHoa ncc : dsNCC)
        {
            Vector<Object> vec = new Vector<Object>();
            vec.add(ncc.getMaHH());
            vec.add(ncc.getTenHH());
            vec.add(ncc.getDVT());
            vec.add(ncc.getGiaban());
            vec.add(ncc.getSlton());            
            vec.add(ncc.getTENNH());                       
            dtb.addRow(vec);
        }
        tbl_danhsachHanghoa.setModel(dtb);
        
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_danhsachHanghoa = new javax.swing.JTable();
        cbo_DVT = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_maHH = new CustomTextField.TextField();
        txt_soluong = new CustomTextField.TextField();
        txt_tenHH = new CustomTextField.TextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_giaban = new CustomTextField.TextField();
        cbo_tenLoaiHH = new combobox.Combobox();
        cbo_dvt = new combobox.Combobox();
        jPanel3 = new javax.swing.JPanel();
        checkbox_timKiemTheoTenhang = new javax.swing.JCheckBox();
        txt_timKiemTenHang = new CustomTextField.TextField();
        txt_timKiemMaHang = new CustomTextField.TextField();
        checkbox_timKiemTheoLoaihang = new javax.swing.JCheckBox();
        checkbox_timKiemTheoMH = new javax.swing.JCheckBox();
        checkbox_timKiem = new javax.swing.JCheckBox();
        btn_timKiem = new CustomButton.Button();
        cbo_tenLoaiHH_TimKiem = new combobox.Combobox();
        txt_maNH = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        btn_luu = new CustomButton.Button();
        btn_them = new CustomButton.Button();
        btn_sua = new CustomButton.Button();
        btn_xoa = new CustomButton.Button();
        btn_xuatpdf = new CustomButton.Button();
        btn_reload = new CustomButton.Button();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 153, 255));
        jLabel8.setText("Danh mục hàng hóa");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(670, 670, 670)
                .addComponent(jLabel8)
                .addContainerGap(567, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbl_danhsachHanghoa.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        tbl_danhsachHanghoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        tbl_danhsachHanghoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_danhsachHanghoaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_danhsachHanghoa);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1588, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        cbo_DVT.setBackground(new java.awt.Color(185, 209, 234));
        cbo_DVT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        cbo_DVT.setPreferredSize(new java.awt.Dimension(372, 662));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("Đơn vị tính");

        jLabel2.setBackground(new java.awt.Color(0, 102, 204));
        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 204));
        jLabel2.setText("Mã hàng");

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 204));
        jLabel4.setText("Loại hàng");

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 204));
        jLabel5.setText("Tên hàng");

        txt_maHH.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txt_maHH.setShadowColor(new java.awt.Color(255, 0, 255));
        txt_maHH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_maHHActionPerformed(evt);
            }
        });

        txt_soluong.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txt_soluong.setShadowColor(new java.awt.Color(255, 0, 255));
        txt_soluong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_soluongActionPerformed(evt);
            }
        });

        txt_tenHH.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txt_tenHH.setShadowColor(new java.awt.Color(255, 0, 255));
        txt_tenHH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tenHHActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 204));
        jLabel3.setText("Số lượng");

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 204));
        jLabel6.setText("Giá Bán");

        txt_giaban.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txt_giaban.setShadowColor(new java.awt.Color(255, 0, 255));
        txt_giaban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_giabanActionPerformed(evt);
            }
        });

        cbo_tenLoaiHH.setEditable(true);
        cbo_tenLoaiHH.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bánh kẹo", "Mỹ phẩm", "Trái cây, rau củ", "............." }));
        cbo_tenLoaiHH.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        cbo_tenLoaiHH.setLabeText("");

        cbo_dvt.setEditable(true);
        cbo_dvt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bánh kẹo", "Mỹ phẩm", "Trái cây, rau củ", "............." }));
        cbo_dvt.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        cbo_dvt.setLabeText("");

        jPanel3.setBackground(new java.awt.Color(38, 176, 227));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        checkbox_timKiemTheoTenhang.setBackground(new java.awt.Color(38, 176, 227));
        checkbox_timKiemTheoTenhang.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        checkbox_timKiemTheoTenhang.setForeground(new java.awt.Color(255, 255, 255));
        checkbox_timKiemTheoTenhang.setText("Tên hàng");

        txt_timKiemTenHang.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txt_timKiemTenHang.setShadowColor(new java.awt.Color(255, 0, 255));
        txt_timKiemTenHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_timKiemTenHangActionPerformed(evt);
            }
        });

        txt_timKiemMaHang.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txt_timKiemMaHang.setShadowColor(new java.awt.Color(255, 0, 255));
        txt_timKiemMaHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_timKiemMaHangActionPerformed(evt);
            }
        });

        checkbox_timKiemTheoLoaihang.setBackground(new java.awt.Color(38, 176, 227));
        checkbox_timKiemTheoLoaihang.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        checkbox_timKiemTheoLoaihang.setForeground(new java.awt.Color(255, 255, 255));
        checkbox_timKiemTheoLoaihang.setText("Loại hàng");

        checkbox_timKiemTheoMH.setBackground(new java.awt.Color(38, 176, 227));
        checkbox_timKiemTheoMH.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        checkbox_timKiemTheoMH.setForeground(new java.awt.Color(255, 255, 255));
        checkbox_timKiemTheoMH.setText("Mã hàng");

        checkbox_timKiem.setBackground(new java.awt.Color(38, 176, 227));
        checkbox_timKiem.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        checkbox_timKiem.setForeground(new java.awt.Color(255, 255, 51));
        checkbox_timKiem.setText("Tìm kiếm");

        btn_timKiem.setForeground(new java.awt.Color(255, 0, 0));
        btn_timKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-search.gif"))); // NOI18N
        btn_timKiem.setText("Tìm kiếm");
        btn_timKiem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_timKiem.setShadowColor(new java.awt.Color(51, 0, 204));
        btn_timKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timKiemActionPerformed(evt);
            }
        });

        cbo_tenLoaiHH_TimKiem.setEditable(true);
        cbo_tenLoaiHH_TimKiem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bánh kẹo", "Mỹ phẩm", "Trái cây, rau củ", "............." }));
        cbo_tenLoaiHH_TimKiem.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        cbo_tenLoaiHH_TimKiem.setLabeText("");
        cbo_tenLoaiHH_TimKiem.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbo_tenLoaiHH_TimKiemItemStateChanged(evt);
            }
        });

        txt_maNH.setText("manh");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(checkbox_timKiemTheoLoaihang)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(checkbox_timKiem)
                        .addComponent(checkbox_timKiemTheoTenhang)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txt_timKiemTenHang, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(checkbox_timKiemTheoMH))
                            .addComponent(cbo_tenLoaiHH_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_timKiemMaHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_timKiem, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(txt_maNH, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkbox_timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_maNH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_timKiemTenHang, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkbox_timKiemTheoTenhang, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkbox_timKiemTheoMH, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_timKiemMaHang, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkbox_timKiemTheoLoaihang, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbo_tenLoaiHH_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout cbo_DVTLayout = new javax.swing.GroupLayout(cbo_DVT);
        cbo_DVT.setLayout(cbo_DVTLayout);
        cbo_DVTLayout.setHorizontalGroup(
            cbo_DVTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cbo_DVTLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(cbo_DVTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cbo_DVTLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_maHH, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(cbo_DVTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(cbo_DVTLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_soluong, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cbo_DVTLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbo_dvt, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cbo_DVTLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(txt_tenHH, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(cbo_DVTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(cbo_DVTLayout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cbo_tenLoaiHH, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(cbo_DVTLayout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_giaban, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        cbo_DVTLayout.setVerticalGroup(
            cbo_DVTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cbo_DVTLayout.createSequentialGroup()
                .addGroup(cbo_DVTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cbo_DVTLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(cbo_DVTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cbo_DVTLayout.createSequentialGroup()
                                .addComponent(txt_tenHH, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(cbo_dvt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addGroup(cbo_DVTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_soluong, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(cbo_DVTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txt_giaban, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(cbo_DVTLayout.createSequentialGroup()
                                .addGroup(cbo_DVTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_maHH, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)
                                .addGroup(cbo_DVTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbo_tenLoaiHH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(cbo_DVTLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(0, 204, 204));

        btn_luu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-save.gif"))); // NOI18N
        btn_luu.setText("Lưu");
        btn_luu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_luu.setShadowColor(new java.awt.Color(51, 0, 204));
        btn_luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_luuActionPerformed(evt);
            }
        });

        btn_them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-plus.gif"))); // NOI18N
        btn_them.setText("Thêm");
        btn_them.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_them.setShadowColor(new java.awt.Color(51, 0, 204));
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-edit_gif.gif"))); // NOI18N
        btn_sua.setText("Sửa");
        btn_sua.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_sua.setShadowColor(new java.awt.Color(0, 0, 204));
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });

        btn_xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-trash.gif"))); // NOI18N
        btn_xoa.setText("Xóa");
        btn_xoa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_xoa.setShadowColor(new java.awt.Color(51, 0, 204));
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        btn_xuatpdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-excel-48.png"))); // NOI18N
        btn_xuatpdf.setText("Execl");
        btn_xuatpdf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_xuatpdf.setShadowColor(new java.awt.Color(51, 0, 204));
        btn_xuatpdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xuatpdfActionPerformed(evt);
            }
        });

        btn_reload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-synchronize.gif"))); // NOI18N
        btn_reload.setText("LOAD");
        btn_reload.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_reload.setShadowColor(new java.awt.Color(51, 0, 204));
        btn_reload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reloadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btn_reload, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(310, 310, 310)
                .addComponent(btn_them, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_luu, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btn_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_xuatpdf, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_them, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_luu, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_xuatpdf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_reload, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbo_DVT, javax.swing.GroupLayout.PREFERRED_SIZE, 1579, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbo_DVT, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_maHHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_maHHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_maHHActionPerformed

    private void txt_soluongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_soluongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_soluongActionPerformed

    private void txt_tenHHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tenHHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tenHHActionPerformed

    private void txt_giabanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_giabanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_giabanActionPerformed

    private void tbl_danhsachHanghoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_danhsachHanghoaMouseClicked
        int n = this.tbl_danhsachHanghoa.getSelectedRow();
        this.txt_maHH.setText(String.valueOf(tbl_danhsachHanghoa.getValueAt(n, 0)));     
        this.txt_tenHH.setText((String)tbl_danhsachHanghoa.getValueAt(n, 1));
        this.cbo_dvt.setSelectedItem((String) tbl_danhsachHanghoa.getValueAt(n, 2));        
        this.txt_giaban.setText(String.valueOf(tbl_danhsachHanghoa.getValueAt(n, 3)));
        this.txt_soluong.setText(String.valueOf(tbl_danhsachHanghoa.getValueAt(n, 4)));    
        this.cbo_tenLoaiHH.setSelectedItem((String) tbl_danhsachHanghoa.getValueAt(n, 5));
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_danhsachHanghoaMouseClicked

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
      txt_giaban.setText("");
      txt_soluong.setText("");
      txt_tenHH.setText("");
      txt_maHH.setText("");                           
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_luuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_luuActionPerformed
    if(txt_giaban.getText().isEmpty() || txt_soluong.getText().isEmpty()||txt_tenHH.getText().isEmpty())
    {
      JOptionPane.showMessageDialog(jPanel4, "Vui lòng nhập đầy đủ thông tin");
    }  
    else
    {              
        try {
                 double giaBan= Double.parseDouble(txt_giaban.getText());
                 int sl= Integer.parseInt(txt_soluong.getText());                   
                 if(giaBan<0||sl<0)
                 {
                        JOptionPane.showMessageDialog(jPanel4, "Không được nhập số âm");
                 }
                 else{
                    HangHoa hh = new HangHoa();     
                    ArrayList<String> tenNH= new ArrayList<String>();
                    tenNH=HangHoaDAO.layDSTenNH();
                    int pos=0;
                    for(int i=0; i<tenNH.size();i++)
                    {                     
                        if(cbo_tenLoaiHH.getSelectedItem().toString().trim().equals(tenNH.get(i).trim())==true)
                        {
                           pos=i+1;                            
                           break;
                        }
                    }                                                                                             
                    try {                           
                        int temp= Integer.parseInt(txt_soluong.getText());
                        double giaban=Double.parseDouble(txt_giaban.getText());
                        
                        hh.setSlton(temp);
                        hh.setGiaban(giaban);
                        hh.setDVT(cbo_dvt.getSelectedItem().toString()); 
                        hh.setMaNH(pos);
                        hh.setTenHH(txt_tenHH.getText());
                        boolean kq= HangHoaDAO.themHH(hh);                    
                        if(kq)
                        {
                          JOptionPane.showMessageDialog(jPanel4, "Thêm thành công");
                        }
                        else
                        {
                          JOptionPane.showMessageDialog(jPanel4, "Thêm thất bại");
                        }
                    
                    }
                    catch (Exception e) {
                        JOptionPane.showMessageDialog(jPanel4, "Số lượng và đơn giá phải là số");
                 }
                 }
       
                                  
        } catch (Exception e) {
            JOptionPane.showMessageDialog(jPanel4, "Số lượng và đơn giá phải là số");
        }
        HienThi_DSHH();
         updateRowHeights();
                                                                                                                                    
    }                            
    }//GEN-LAST:event_btn_luuActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
      
            int maHH= Integer.parseInt(txt_maHH.getText());                
            boolean kq= HangHoaDAO.xoaHH(maHH);
            if(kq==true)
            {
                JOptionPane.showMessageDialog(this,"Xóa thành công");
            }
            else
            {
                 JOptionPane.showMessageDialog(this,"Xóa thất bại");
            }               
        HienThi_DSHH();
         updateRowHeights();
        
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
  if(txt_giaban.getText().isEmpty() || txt_soluong.getText().isEmpty()||txt_tenHH.getText().isEmpty())
    {
      JOptionPane.showMessageDialog(jPanel4, "Vui lòng nhập đầy đủ thông tin");
    }  
    else
    {              
        try {
                 double giaBan= Double.parseDouble(txt_giaban.getText());
                 int sl= Integer.parseInt(txt_giaban.getText());                   
                 if(giaBan<0||sl<0)
                 {
                        JOptionPane.showMessageDialog(jPanel4, "Không được nhập số âm");
                 }
                 else{
                    HangHoa hh = new HangHoa();     
                    ArrayList<String> tenNH= new ArrayList<String>();
                    tenNH=HangHoaDAO.layDSTenNH();
                    int pos=0;
                    for(int i=0; i<tenNH.size();i++)
                    {                     
                        if(cbo_tenLoaiHH.getSelectedItem().toString().trim().equals(tenNH.get(i).trim())==true)
                        {
                           pos=i+1;                            
                           break;
                        }
                    }                                                                                             
                    try {                           
                        int temp= Integer.parseInt(txt_soluong.getText());  // số lượng
                        double giaban=Double.parseDouble(txt_giaban.getText());   //Đơn giá                        
                        hh.setSlton(temp);
                        hh.setGiaban(giaban);
                        hh.setDVT(cbo_dvt.getSelectedItem().toString()); 
                        hh.setMaNH(pos);
                        hh.setTenHH(txt_tenHH.getText());
                        hh.setMaHH(Integer.parseInt(txt_maHH.getText()));                                                
                        boolean kq= HangHoaDAO.suaHH(hh);      
                             System.out.println("mahh :" + hh.getMaHH() );
                             System.out.println("mahh:  " + hh.getMaNH());
                             System.out.println("mahh:  " + hh.getTenHH());
                             System.out.println("mahh:  " + hh.getDVT());
                             System.out.println("mahh:  " + hh.getGiaban());
                             System.out.println("mahh:  " + hh.getSlton());
                        if(kq)
                        {
                          JOptionPane.showMessageDialog(jPanel4, "Cập nhật thành công");
                        }
                        else
                        {
                          JOptionPane.showMessageDialog(jPanel4, "Cập nhật thất bại");
                        }
                    
                    }
                    catch (Exception e) {
                        JOptionPane.showMessageDialog(jPanel4, "Số lượng và đơn giá phải là số");
                 }
                 }
       
                 
                 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(jPanel4, "Số lượng và đơn giá phải là số");
        }
        HienThi_DSHH();
        updateRowHeights();
    }
        
    }//GEN-LAST:event_btn_suaActionPerformed

    private void txt_timKiemTenHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_timKiemTenHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_timKiemTenHangActionPerformed

    private void txt_timKiemMaHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_timKiemMaHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_timKiemMaHangActionPerformed

    private void btn_xuatpdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xuatpdfActionPerformed
      
        try {
            XSSFWorkbook workbook = new XSSFWorkbook();           
            XSSFSheet spreadsheet = workbook.createSheet("DSHH");            
            XSSFRow row = null;
            Cell cell = null;
            
            row = spreadsheet.createRow((short) 2);
            row.setHeight((short) 500);
            cell = row.createCell(0, CellType.STRING);
            cell.setCellValue("DANH SÁCH HÀNG HÓA");
            row = spreadsheet.createRow((short) 3);
            row.setHeight((short) 500);
            
            cell = row.createCell(0, CellType.STRING);
            cell.setCellValue("Mã ");       
            cell = row.createCell(1, CellType.STRING);
            cell.setCellValue("Tên SP");
            cell = row.createCell(2, CellType.STRING);
            cell.setCellValue("Đơn vị tính");
            cell = row.createCell(3, CellType.STRING);
            cell.setCellValue("Giá bán");
            cell = row.createCell(4, CellType.STRING);
            cell.setCellValue("Số lượng");
            cell = row.createCell(5, CellType.STRING);
            cell.setCellValue("Loại hàng hóa");
                System.out.println("trung2");
              ArrayList<HangHoa> dsHH = HangHoaDAO.layDSHangHoa();
               System.out.println(dsHH);
            for (int i = 0; i < dsHH.size(); i++) {
                    HangHoa hh = dsHH.get(i);
                    row = spreadsheet.createRow((short) 4 + i);
                    row.setHeight((short) 400);
                    row.createCell(0).setCellValue(hh.getMaHH());
                    row.createCell(1).setCellValue(hh.getTenHH());
                    row.createCell(2).setCellValue(hh.getDVT());
                    row.createCell(3).setCellValue(hh.getGiaban());
                    row.createCell(4).setCellValue(hh.getSlton());
                    row.createCell(5).setCellValue(hh.getTENNH());
            }
               File  f = new File("D://danhsachHH.xlsx");
            try {                  
                    FileOutputStream out = new FileOutputStream(f);
                    workbook.write(out);
                    out.close();
                    JOptionPane.showMessageDialog(this, "Đã xuất file Excel");
                    System.out.println("xuat thanh cong");
           } catch (FileNotFoundException ex) {
               ex.printStackTrace();
           }
           
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_xuatpdfActionPerformed

    private void btn_timKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timKiemActionPerformed
       if(checkbox_timKiem.isSelected())
       {
           if(checkbox_timKiemTheoTenhang.isSelected())
           {
                ArrayList<HangHoa> dsHH = HangHoaDAO.timKiemTheoTenHang(txt_timKiemTenHang.getText().trim());
                DefaultTableModel dtb = (DefaultTableModel)tbl_danhsachHanghoa.getModel();
                dtb.setRowCount(0);
                for(HangHoa ncc : dsHH)
                {
                    Vector<Object> vec = new Vector<Object>();
                    vec.add(ncc.getMaHH());
                    vec.add(ncc.getTenHH());
                    vec.add(ncc.getDVT());
                    vec.add(ncc.getGiaban());
                    vec.add(ncc.getSlton());            
                    vec.add(ncc.getTENNH());                       
                    dtb.addRow(vec);
                }
                tbl_danhsachHanghoa.setModel(dtb);
                updateRowHeights();
           }
           else if(checkbox_timKiemTheoMH.isSelected())
           {
                int maHH= Integer.parseInt(txt_timKiemMaHang.getText().trim());
                ArrayList<HangHoa> dsHH = HangHoaDAO.timKiemTheoMaHang(maHH);
                DefaultTableModel dtb = (DefaultTableModel)tbl_danhsachHanghoa.getModel();
                dtb.setRowCount(0);
                for(HangHoa ncc : dsHH)
                {
                    Vector<Object> vec = new Vector<Object>();
                    vec.add(ncc.getMaHH());
                    vec.add(ncc.getTenHH());
                    vec.add(ncc.getDVT());
                    vec.add(ncc.getGiaban());
                    vec.add(ncc.getSlton());            
                    vec.add(ncc.getTENNH());                       
                    dtb.addRow(vec);
                }
                tbl_danhsachHanghoa.setModel(dtb);
                updateRowHeights();
           }
           else
           {
               int maHH= Integer.parseInt(txt_maNH.getText().trim());
                ArrayList<HangHoa> dsHH = HangHoaDAO.timKiemTheoMaNH(maHH);
                DefaultTableModel dtb = (DefaultTableModel)tbl_danhsachHanghoa.getModel();
                dtb.setRowCount(0);
                for(HangHoa ncc : dsHH)
                {
                    Vector<Object> vec = new Vector<Object>();
                    vec.add(ncc.getMaHH());
                    vec.add(ncc.getTenHH());
                    vec.add(ncc.getDVT());
                    vec.add(ncc.getGiaban());
                    vec.add(ncc.getSlton());            
                    vec.add(ncc.getTENNH());                       
                    dtb.addRow(vec);
                }
                tbl_danhsachHanghoa.setModel(dtb);
                updateRowHeights();
           }
       }
    }//GEN-LAST:event_btn_timKiemActionPerformed

    private void btn_reloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reloadActionPerformed
        HienThi_DSHH();
        updateRowHeights();
    }//GEN-LAST:event_btn_reloadActionPerformed

    private void cbo_tenLoaiHH_TimKiemItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbo_tenLoaiHH_TimKiemItemStateChanged
              
        int i = cbo_tenLoaiHH_TimKiem.getSelectedIndex();
        int t = i + 1;       
        txt_maNH.setText(String.valueOf(t));   
    }//GEN-LAST:event_cbo_tenLoaiHH_TimKiemItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private CustomButton.Button btn_luu;
    private CustomButton.Button btn_reload;
    private CustomButton.Button btn_sua;
    private CustomButton.Button btn_them;
    private CustomButton.Button btn_timKiem;
    private CustomButton.Button btn_xoa;
    private CustomButton.Button btn_xuatpdf;
    private javax.swing.JPanel cbo_DVT;
    private combobox.Combobox cbo_dvt;
    private combobox.Combobox cbo_tenLoaiHH;
    private combobox.Combobox cbo_tenLoaiHH_TimKiem;
    private javax.swing.JCheckBox checkbox_timKiem;
    private javax.swing.JCheckBox checkbox_timKiemTheoLoaihang;
    private javax.swing.JCheckBox checkbox_timKiemTheoMH;
    private javax.swing.JCheckBox checkbox_timKiemTheoTenhang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_danhsachHanghoa;
    private CustomTextField.TextField txt_giaban;
    private CustomTextField.TextField txt_maHH;
    private javax.swing.JTextField txt_maNH;
    private CustomTextField.TextField txt_soluong;
    private CustomTextField.TextField txt_tenHH;
    private CustomTextField.TextField txt_timKiemMaHang;
    private CustomTextField.TextField txt_timKiemTenHang;
    // End of variables declaration//GEN-END:variables
}
