/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.raven.form;

import dao.NhaCCDAO;
import dao.PhieuNhapDAO;
import dao.ThongKe_HD_DAO;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import pojo.NhaCungCap;
import pojo.PhieuNhap;
import pojo.ThongKe_HD;
import swing.chart.ModelPieChart;
import swing.chart.PieChart;

/**
 *
 * @author RAVEN
 */
public class Form_ThongKe_SP extends javax.swing.JPanel {

    String tieude[]={"Mã hàng", "Tên Hàng", "Tổng số lượng"};
    DefaultTableModel tbl_mode = new DefaultTableModel();
    /**
     * Creates new form Form_1
     */
    public Form_ThongKe_SP() {
        initComponents();
        DefaultTableModel tblModel;
        tblModel = (DefaultTableModel) this.tbl_danhsach.getModel();
        tbl_mode.setColumnIdentifiers(tieude);
        tbl_danhsach.setModel(tbl_mode);        
        HienThi_CBo_Thang();
        
        HienThi_CBo_Thang();
        HienThi_CBo_Nam();
       chinhFont();
//        getContentPane().setBackground(new Color(255, 255, 255));
//        pieChart1.setChartType(PieChart.PeiChartType.DONUT_CHART);
//        pieChart1.addData(new ModelPieChart("Tigher", 150, new Color(23, 126, 238)));
//        pieChart1.addData(new ModelPieChart("ABC", 100, new Color(221, 65, 65)));
//        pieChart1.addData(new ModelPieChart("Coca", 1, new Color(47, 157, 64)));
//        pieChart1.addData(new ModelPieChart("Vita", 60, new Color(196, 151, 58)));

    }
       private void updateRowHeights()
    {
        for (int row = 0; row < tbl_danhsach.getRowCount(); row++)
        {
            int rowHeight = tbl_danhsach.getRowHeight();

            for (int column = 0; column < tbl_danhsach.getColumnCount(); column++)
            {
                Component comp = tbl_danhsach.prepareRenderer(tbl_danhsach.getCellRenderer(row, column), row, column);
                rowHeight = Math.max(rowHeight, comp.getPreferredSize().height);
            }

            tbl_danhsach.setRowHeight(row, rowHeight);
        }
              
    }
        public void chinhFont()
    {
        tbl_danhsach.getTableHeader().setFont(new Font("SansSerif", Font.BOLD, 20)); // chỉnh font chữ lại cho title
        tbl_danhsach.getTableHeader().setFont(new Font("SansSerif", Font.BOLD, 20));
    }
    private void HienThi_CBo_Thang(){
        ArrayList<ThongKe_HD> dsThang = ThongKe_HD_DAO.layThang();
        //DefaultTableModel tbmode = (DefaultTableModel) tbl_danhsach.getModel();
        DefaultComboBoxModel cbomode = (DefaultComboBoxModel) cbo_thang.getModel();
        DefaultComboBoxModel cbomode_nam = (DefaultComboBoxModel) cbo_nam.getModel();
        cbo_thang.removeAllItems(); // xóa hết dl trong cbo
        cbo_nam.removeAllItems(); // xóa hết dl trong cbo
        for(ThongKe_HD ncc : dsThang)
        {   
            cbomode.addElement(ncc.getThang());
            cbomode_nam.addElement(ncc.getNam());
        }
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbo_thang = new combobox.Combobox();
        btn_luu_pn = new CustomButton.Button();
        cbo_nam = new combobox.Combobox();
        jPanel4 = new javax.swing.JPanel();
        pieChart = new swing.chart.PieChart();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_danhsach = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(38, 176, 227));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 2));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("1. Tháng");

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("2. Năm");

        cbo_thang.setEditable(true);
        cbo_thang.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nhà cung cấp 1", "Nhà cung cấp 2", "Nhà cung cấp 3", "" }));
        cbo_thang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbo_thang.setLabeText("");
        cbo_thang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_thangActionPerformed(evt);
            }
        });

        btn_luu_pn.setForeground(new java.awt.Color(255, 0, 0));
        btn_luu_pn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-save (1).gif"))); // NOI18N
        btn_luu_pn.setText("Thống kê");
        btn_luu_pn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_luu_pn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_luu_pnActionPerformed(evt);
            }
        });

        cbo_nam.setEditable(true);
        cbo_nam.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nhà cung cấp 1", "Nhà cung cấp 2", "Nhà cung cấp 3", "" }));
        cbo_nam.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbo_nam.setLabeText("");
        cbo_nam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_namActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbo_nam, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbo_thang, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(btn_luu_pn, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbo_thang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbo_nam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(btn_luu_pn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(pieChart, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(pieChart, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        tbl_danhsach.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        tbl_danhsach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_danhsach);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1004, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(231, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 153, 255));
        jLabel8.setText("Thống Kê Sản Phẩm");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(651, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(599, 599, 599))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbo_thangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_thangActionPerformed
        // TODO add your handling code here:
//        if(cbo_thang.getSelectedIndex() >= 0)
//        {
//            int nam = Integer.valueOf(cbo_nam.getSelectedItem().toString());
//            int thang = Integer.valueOf(cbo_thang.getSelectedItem().toString());
//            ThongKe_HD tk = (ThongKe_HD) cbo_thang.getSelectedItem();
//            showDL(nam,thang);
//        }
    }//GEN-LAST:event_cbo_thangActionPerformed

    private void btn_luu_pnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_luu_pnActionPerformed
        // TODO add your handling code here:
        
        int n = Integer.parseInt(cbo_nam.getSelectedItem().toString());
        int t = Integer.parseInt(cbo_thang.getSelectedItem().toString());
        showDL(n,t);
        updateRowHeights();
        

    }//GEN-LAST:event_btn_luu_pnActionPerformed

    private void cbo_namActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_namActionPerformed
        // TODO add your handling code here:
//        if(cbo_nam.getSelectedIndex() >= 0)
//        {
//            int year = Integer.valueOf(cbo_nam.getSelectedItem().toString());
//            cbo_nam.removeAllItems();
//            
//            
//        }
    }//GEN-LAST:event_cbo_namActionPerformed
    
   
    
    private void HienThi_CBo_Nam() {
        ArrayList<PhieuNhap> dsThang = PhieuNhapDAO.lay_CBo_nam();
        //DefaultTableModel tbmode = (DefaultTableModel) tbl_danhsach.getModel();
        DefaultComboBoxModel cbomode = (DefaultComboBoxModel) cbo_nam.getModel();
        cbo_nam.removeAllItems(); // xóa hết dl trong cbo
        for(PhieuNhap pn : dsThang)
        {   
            cbomode.addElement(pn.getNgayNhap());
        }
        

    }
    
    private void showDL(int nam, int thang){
       pieChart.clearData();
        nam = Integer.parseInt(cbo_nam.getSelectedItem().toString());
        thang = Integer.parseInt(cbo_thang.getSelectedItem().toString());
        ArrayList<ThongKe_HD> dsPN = ThongKe_HD_DAO.lay_DS_SP_BanChay_TrongThang(nam, thang);
        DefaultTableModel dtb = (DefaultTableModel)tbl_danhsach.getModel();
        dtb.setRowCount(0);
        int index = 0;
        for(ThongKe_HD pn : dsPN)
        {
            Vector<Object> vec = new Vector<Object>();
            vec.add(pn.getMaHH());
            vec.add(pn.getTenHH());
            vec.add(pn.getTongSL());

            pieChart.addData(new ModelPieChart(pn.getTenHH(), pn.getTongSL(), getColor(index++)));
            dtb.addRow(vec);
        }
        tbl_danhsach.setModel(dtb);
        //tbl_danhsach.setModel(dtb);
    }
    private Color getColor(int index)
    {   
        Color color1 = new Color(0, 255, 0);
        Color color2 = new Color(0, 0, 255);
        Color color3 = new Color(255, 255, 0);
        Color color4 = new Color(0, 255, 255);
        Color color5 = new Color(255,0,255);
        Color color6 = new Color(255,160,122);
        Color color7 = new Color(220,20,60);
        Color color8 = new Color(139,0,0);
        Color color9 = new Color(255,69,0);
        Color color10 = new Color(127,255,0);
        Color color11 = new Color(50,205,50);
        Color color12 = new Color(34,139,34);
        Color color13 = new Color(0, 255, 255);
        Color color14 = new Color(0, 255, 255);
        Color color15 = new Color(0, 255, 255);
        
        Color[] color = new Color[]{color1,color2,color3,color4,color5,color6,color7,color8,color9,color10};
        return color[index];
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private CustomButton.Button btn_luu_pn;
    private combobox.Combobox cbo_nam;
    private combobox.Combobox cbo_thang;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private swing.chart.PieChart pieChart;
    private javax.swing.JTable tbl_danhsach;
    // End of variables declaration//GEN-END:variables
}

    

