/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.raven.form;

import dao.PhieuNhapDAO;
import java.awt.Component;
import java.awt.Font;
import java.sql.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import pojo.PhieuNhap;

/**
 *
 * @author RAVEN
 */
public class Form_DanhSachPhieuNhap extends javax.swing.JPanel {

    String tieude[]={"Mã phiếu nhập", "Tên nhà cung cấp", "Ngày Nhập", "Tổng nhập"};
    DefaultTableModel tbl_mode = new DefaultTableModel();
    DateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy");
    Date date;
    /**
     * Creates new form Form_1
     */
    public Form_DanhSachPhieuNhap() {
        initComponents();
        DefaultTableModel tblModel;
        tblModel = (DefaultTableModel) this.tbl_dsPN.getModel();
        tbl_mode.setColumnIdentifiers(tieude);
        tbl_dsPN.setModel(tbl_mode);
        HienThi_PN();
        updateRowHeights();
    }
  public void HienThi_PN() {
        ArrayList<PhieuNhap> dsPN = PhieuNhapDAO.layDSPN();
        DefaultTableModel dtb = (DefaultTableModel)tbl_dsPN.getModel();
        dtb.setRowCount(0);
        for(PhieuNhap pn : dsPN)
        {
            Vector<Object> vec = new Vector<Object>();
            vec.add(pn.getMaPN());
            vec.add(pn.getTenNCC());
            vec.add(pn.getNgayNhap());
            vec.add(pn.getTongNhap());
           
            dtb.addRow(vec);
        }
        tbl_dsPN.setModel(dtb);
        chinhFont();
        
    }
  
    private void updateRowHeights()
    {
        for (int row = 0; row < tbl_dsPN.getRowCount(); row++)
        {
            int rowHeight = tbl_dsPN.getRowHeight();

            for (int column = 0; column < tbl_dsPN.getColumnCount(); column++)
            {
                Component comp = tbl_dsPN.prepareRenderer(tbl_dsPN.getCellRenderer(row, column), row, column);
                rowHeight = Math.max(rowHeight, comp.getPreferredSize().height);
            }

            tbl_dsPN.setRowHeight(row, rowHeight);
        }
              
    }
   public void chinhFont()
    {
        tbl_dsPN.getTableHeader().setFont(new Font("SansSerif", Font.BOLD, 20)); // chỉnh font chữ lại cho title
        tbl_dsPN.getTableHeader().setFont(new Font("SansSerif", Font.BOLD, 20));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_dsPN = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        button3 = new CustomButton.Button();
        button4 = new CustomButton.Button();
        txt_timKiemTenHang = new CustomTextField.TextField();
        btn_timKiem = new CustomButton.Button();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        tbl_dsPN.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tbl_dsPN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(tbl_dsPN);

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setFocusCycleRoot(true);

        button3.setBackground(new java.awt.Color(51, 204, 255));
        button3.setText("Xuất báo cáo");
        button3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        button3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        button3.setShadowColor(new java.awt.Color(51, 0, 204));

        button4.setBackground(new java.awt.Color(255, 204, 0));
        button4.setText("Xem chi tiết");
        button4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button4.setShadowColor(new java.awt.Color(204, 0, 153));

        txt_timKiemTenHang.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txt_timKiemTenHang.setShadowColor(new java.awt.Color(255, 0, 255));
        txt_timKiemTenHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_timKiemTenHangActionPerformed(evt);
            }
        });

        btn_timKiem.setForeground(new java.awt.Color(255, 0, 0));
        btn_timKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-search.gif"))); // NOI18N
        btn_timKiem.setText("Tìm kiếm");
        btn_timKiem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_timKiem.setShadowColor(new java.awt.Color(51, 0, 204));
        btn_timKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timKiemActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setText("Số PN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addComponent(txt_timKiemTenHang, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btn_timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(944, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_timKiemTenHang, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 22, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 153, 255));
        jLabel9.setText("Danh sách phiếu nhập");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(670, 670, 670)
                .addComponent(jLabel9)
                .addContainerGap(390, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_timKiemTenHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_timKiemTenHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_timKiemTenHangActionPerformed

    private void btn_timKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_timKiemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private CustomButton.Button btn_timKiem;
    private CustomButton.Button button3;
    private CustomButton.Button button4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_dsPN;
    private CustomTextField.TextField txt_timKiemTenHang;
    // End of variables declaration//GEN-END:variables
}
