/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.raven.form;

import static com.raven.form.Form_LapPhieuNhapHang.now;
import com.raven.main.Main;
import dao.CT_PhieuNhapDAO;
import dao.ChucVuDAO;
import dao.HangHoaDAO;
import dao.PhieuNhapDAO;
import dao.ThongKe_HD_DAO;
import java.awt.Component;
import java.awt.Font;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pojo.Aprior_2;
import pojo.Apriori;
import pojo.CT_PhieuNhap;
import pojo.ChucVu;
import pojo.HangHoa;
import pojo.PhieuNhap;
import pojo.ThongKe_HD;

/**
 *
 * @author LinhPTA-PC
 */
public class Form_ChiTiet_PN extends javax.swing.JFrame {
   
    String tieude[] = {"Tên hàng", "Số lượng", "Giá nhập", "Thành tiền"};
    DefaultTableModel tbl_mode = new DefaultTableModel();
    int mapn = PhieuNhapDAO.layMAPN_moiThem();   
    int tongtien = 0;
    
    String tieude_dx[] = {"Mã hàng", "Tên hàng hóa", "Tổng số lượng"};
    DefaultTableModel tbl_mode_dx = new DefaultTableModel();
    /**
     * Creates new form Form_ChiTiet_PN
     */   
    public Form_ChiTiet_PN() {
        initComponents();

        DefaultTableModel tblModel;
        tblModel = (DefaultTableModel) this.tbl_danhsach.getModel();
        tbl_mode.setColumnIdentifiers(tieude);
        tbl_danhsach.setModel(tbl_mode);
        
        DefaultTableModel tblModel_dx;
        tblModel_dx = (DefaultTableModel) this.tbl_danhsach_goi_y1.getModel();
        tbl_mode_dx.setColumnIdentifiers(tieude_dx);
        tbl_danhsach_goi_y1.setModel(tbl_mode_dx);
       
        txt_mapn.setEnabled(false);
        hienThi_cbo_HH();
        chinhFont();
        CT_PhieuNhapDAO.layDSMaHH();
        
    }
     public void chinhFont()
    {
        tbl_danhsach.getTableHeader().setFont(new Font("Times New Roman", Font.BOLD, 23)); // chỉnh font chữ lại cho title
        tbl_danhsach.getTableHeader().setFont(new Font("Times New Roman", Font.BOLD, 23));
    }
     private void updateRowHeights()
      {
        for (int row = 0; row < tbl_danhsach.getRowCount(); row++)
        {
            int rowHeight = tbl_danhsach.getRowHeight();

            for (int column = 0; column < tbl_danhsach.getColumnCount(); column++)
            {
                Component comp = tbl_danhsach.prepareRenderer(tbl_danhsach.getCellRenderer(row, column), row, column);
                rowHeight = Math.max(rowHeight, comp.getPreferredSize().height);
            }

            tbl_danhsach.setRowHeight(row, rowHeight);
        }
              
    }
    public Form_ChiTiet_PN(int ma)
    {

        initComponents();
        DefaultTableModel tblModel;
        tblModel = (DefaultTableModel) this.tbl_danhsach.getModel();
        tbl_mode.setColumnIdentifiers(tieude);
        tbl_danhsach.setModel(tbl_mode);
        txt_mapn.setEnabled(false);
        hienThi_cbo_HH();
        txt_mapn.setText(String.valueOf(mapn));
        this.mapn = ma;
        this.setLocationRelativeTo(null);
    }
    
    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_mapn = new CustomTextField.TextField();
        button3 = new CustomButton.Button();
        button1 = new CustomButton.Button();
        button2 = new CustomButton.Button();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_sl = new CustomTextField.TextField();
        txt_gianhap = new CustomTextField.TextField();
        cbo_hanghoa = new combobox.Combobox();
        btn_luu_CTPN = new CustomButton.Button();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_danhsach = new javax.swing.JTable();
        btn_TinhTien = new CustomButton.Button();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbl_danhsach_goi_y1 = new javax.swing.JTable();
        button9 = new CustomButton.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 153, 255));
        jLabel8.setText("Chi Tiết Phiếu Nhập");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(707, 707, 707)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 25, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBackground(new java.awt.Color(38, 176, 227));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 2));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Mã phiếu nhập");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Giá nhập");

        txt_mapn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_mapn.setShadowColor(new java.awt.Color(255, 0, 255));
        txt_mapn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_mapnActionPerformed(evt);
            }
        });

        button3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-plus.gif"))); // NOI18N
        button3.setText("Thêm");
        button3.setShadowColor(new java.awt.Color(51, 0, 204));
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });

        button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-trash.gif"))); // NOI18N
        button1.setText("Xóa");
        button1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button1.setShadowColor(new java.awt.Color(51, 0, 204));

        button2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-edit2.gif"))); // NOI18N
        button2.setText("Sửa");
        button2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button2.setShadowColor(new java.awt.Color(0, 0, 204));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Hàng hóa");

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Số lượng");

        txt_sl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_sl.setShadowColor(new java.awt.Color(255, 0, 255));
        txt_sl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_slActionPerformed(evt);
            }
        });

        txt_gianhap.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_gianhap.setShadowColor(new java.awt.Color(255, 0, 255));
        txt_gianhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_gianhapActionPerformed(evt);
            }
        });

        cbo_hanghoa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "hàng hóa" }));
        cbo_hanghoa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbo_hanghoa.setLabeText("");

        btn_luu_CTPN.setForeground(new java.awt.Color(255, 0, 0));
        btn_luu_CTPN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-save (1).gif"))); // NOI18N
        btn_luu_CTPN.setText("Lưu");
        btn_luu_CTPN.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_luu_CTPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_luu_CTPNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(btn_luu_CTPN, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_mapn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_sl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_gianhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbo_hanghoa, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_mapn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbo_hanghoa, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_gianhap, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_luu_CTPN, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(txt_sl, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(398, 398, 398))))
        );

        jPanel3.setBackground(new java.awt.Color(38, 176, 227));

        tbl_danhsach.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        tbl_danhsach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_danhsach);

        btn_TinhTien.setForeground(new java.awt.Color(255, 0, 0));
        btn_TinhTien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-cash-in-hand-48.png"))); // NOI18N
        btn_TinhTien.setText("Tính Tiền");
        btn_TinhTien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_TinhTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TinhTienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(btn_TinhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_TinhTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(38, 176, 227));
        jPanel7.setPreferredSize(new java.awt.Dimension(947, 533));

        tbl_danhsach_goi_y1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tbl_danhsach_goi_y1);

        button9.setBackground(new java.awt.Color(153, 255, 153));
        button9.setText("Đề xuất");
        button9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button9.setShadowColor(new java.awt.Color(51, 0, 204));
        button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(button9, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(button9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void txt_mapnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_mapnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mapnActionPerformed

    private void txt_slActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_slActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_slActionPerformed

    private void txt_gianhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_gianhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_gianhapActionPerformed

    private void btn_TinhTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TinhTienActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Tổng giá trị phiếu nhập là: " + tongtien);
        CT_PhieuNhapDAO.capnhat_TongTien(Integer.parseInt(txt_mapn.getText()));
        this.hide();

    }//GEN-LAST:event_btn_TinhTienActionPerformed

    private void btn_luu_CTPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_luu_CTPNActionPerformed
        // TODO add your handling code here:
        int mahh = cbo_hanghoa.getSelectedIndex();
        mahh++;   
        
        
        CT_PhieuNhap ctpn = new CT_PhieuNhap();
        ctpn.setMaHH(mahh);
        ctpn.setMaPN(Integer.parseInt(txt_mapn.getText()));
        ctpn.setSL(Integer.parseInt(txt_sl.getText()));
        ctpn.setGianhap(Integer.parseInt(txt_gianhap.getText()));
        ctpn.setThanhTien(0);
        
        if (CT_PhieuNhapDAO.them_CTPN(ctpn))
        {
            JOptionPane.showMessageDialog(this, "Thêm sản phẩm thành công!!!");
            int sl = Integer.parseInt(txt_sl.getText());
            int gianhap = Integer.parseInt(txt_gianhap.getText());
            tongtien = tongtien + (sl*gianhap);
            HienThi_CTPN(); 
            updateRowHeights();
            chinhFont();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Thêm phiếu nhập thất bại!!!");
        }
    }//GEN-LAST:event_btn_luu_CTPNActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
 
        
    }//GEN-LAST:event_formWindowClosing
    
    public void HienThi_DeXuat() {
        //ArrayList<ThongKe_HD> dsPN = ThongKe_HD_DAO.lay_DS_SP_BanChay();
        ArrayList<ArrayList<String>> dsDX = Aprior_2.ListDX();
        DefaultTableModel dtb = (DefaultTableModel)tbl_danhsach_goi_y1.getModel();
        dtb.setRowCount(0);
        /*for(ThongKe_HD pn : dsPN)
        {
            Vector<Object> vec = new Vector<Object>();
            vec.add(pn.getMaHH());
            vec.add(pn.getTenHH());
            vec.add(pn.getTongSL());
            
           
            dtb.addRow(vec);
        }*/
        
//        ArrayList<String> dx1 = dsDX.get(0);
//        ArrayList<String> dx2 = dsDX.get(1);
//        ArrayList<String> dx3 = dsDX.get(2);
//        ArrayList<String> dx4 = dsDX.get(3);
//        ArrayList<String> dx5 = dsDX.get(4);
        ArrayList<String> dexuat = new ArrayList<String>();
        for(int i = 0; i < dsDX.size(); i++) {
            for(int j = 0; j < dsDX.get(i).size(); j++) {
                
                System.out.println(dsDX.get(i).get(j));
                dexuat.add(dsDX.get(i).get(j));
                
        }
   
    }
        for(int i = 0; i < dexuat.size(); i++)
        {
            String s = dexuat.get(i);
            String s1 = HangHoaDAO.layDSTenHH(Integer.parseInt(s));
            Vector<String> vec = new Vector<String>();
            vec.add(s);
            vec.add(s1);
            dtb.addRow(vec);
        }
        tbl_danhsach_goi_y1.setModel(dtb);
        
        
        }

   
    private void button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button9ActionPerformed
        // TODO add your handling code here:
        HienThi_DeXuat();
        
    }//GEN-LAST:event_button9ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_ChiTiet_PN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_ChiTiet_PN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_ChiTiet_PN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_ChiTiet_PN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Form_ChiTiet_PN ctpn = new Form_ChiTiet_PN();
                ctpn.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private CustomButton.Button btn_TinhTien;
    private CustomButton.Button btn_luu_CTPN;
    private CustomButton.Button button1;
    private CustomButton.Button button2;
    private CustomButton.Button button3;
    private CustomButton.Button button9;
    private combobox.Combobox cbo_hanghoa;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tbl_danhsach;
    private javax.swing.JTable tbl_danhsach_goi_y1;
    private CustomTextField.TextField txt_gianhap;
    private CustomTextField.TextField txt_mapn;
    private CustomTextField.TextField txt_sl;
    // End of variables declaration//GEN-END:variables

    private void hienThi_cbo_HH() {
        ArrayList<HangHoa> dsHH = HangHoaDAO.layDSHangHoa();
        DefaultTableModel tbmode = (DefaultTableModel) tbl_danhsach.getModel();
        DefaultComboBoxModel cbomode = (DefaultComboBoxModel) cbo_hanghoa.getModel();
        cbo_hanghoa.removeAllItems(); // xóa hết dl trong cbo
        for(HangHoa hh : dsHH)
        {   
            cbomode.addElement(hh.getTenHH());

        }
    }
    

    private void HienThi_CTPN() {
        ArrayList<CT_PhieuNhap> dsPN = CT_PhieuNhapDAO.layDS_CTPN();
        DefaultTableModel dtb = (DefaultTableModel)tbl_danhsach.getModel();
        dtb.setRowCount(0);
        for(CT_PhieuNhap pn : dsPN)
        {
            Vector<Object> vec = new Vector<Object>();
            //vec.add(pn.getMaPN());
            vec.add(pn.getTenHH());
            vec.add(pn.getSL());
            vec.add(pn.getGianhap());
            vec.add(pn.getThanhTien());
            //tongtien = tongtien + pn.getThanhTien();
           
            dtb.addRow(vec);
        }
        tbl_danhsach.setModel(dtb);
    }
}
