/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.raven.form;

import dao.PhieuNhapDAO;
import dao.dsHDDAO;
import java.awt.Component;
import java.awt.Font;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Hashtable;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import pojo.HoaDon;
import pojo.PhieuNhap;

/**
 *
 * @author RAVEN
 */
public class Form_DanhSachHoaDon extends javax.swing.JPanel {

    String tieude[]={"Mã HD", "Tên nhân viên", "Ngày lập", "Tổng tiền", "Mã KH"};
    DefaultTableModel tbl_mode = new DefaultTableModel();
    DateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy");
    Date date;
     public static final String DateFormat = "dd/MM/yyyy";
    /**
     * Creates new form Form_1
     */
    public Form_DanhSachHoaDon() {
        initComponents();
         DefaultTableModel tblModel;
        tblModel = (DefaultTableModel) this.tbl_dsHD.getModel();
        tbl_mode.setColumnIdentifiers(tieude);
        tbl_dsHD.setModel(tbl_mode);                      
        hienThi();
        updateRowHeights();
        chinhFont();
        txt_makh.setVisible(false);
    }
    public void chinhFont()
    {
        tbl_dsHD.getTableHeader().setFont(new Font("SansSerif", Font.BOLD, 20)); // chỉnh font chữ lại cho title
        tbl_dsHD.getTableHeader().setFont(new Font("SansSerif", Font.BOLD, 20));
    }
    
    public void hienThi()
    {
        ArrayList<HoaDon> dsHD = dsHDDAO.layDSHD();
        DefaultTableModel dtb = (DefaultTableModel)tbl_dsHD.getModel();
        dtb.setRowCount(0);
        for(HoaDon hd : dsHD)
        {
            Vector<Object> vec = new Vector<Object>();
            vec.add(hd.getMaHD());
            vec.add(hd.getTenNV());
            vec.add(hd.getNgayBan());
            vec.add(hd.getTongTien());
            vec.add(hd.getTenKH());
            dtb.addRow(vec);
        }
        tbl_dsHD.setModel(dtb);
        
    }
        private void updateRowHeights()
    {
        for (int row = 0; row < tbl_dsHD.getRowCount(); row++)
        {
            int rowHeight = tbl_dsHD.getRowHeight();

            for (int column = 0; column < tbl_dsHD.getColumnCount(); column++)
            {
                Component comp = tbl_dsHD.prepareRenderer(tbl_dsHD.getCellRenderer(row, column), row, column);
                rowHeight = Math.max(rowHeight, comp.getPreferredSize().height);
            }

            tbl_dsHD.setRowHeight(row, rowHeight);
        }
              
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_dsHD = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        button4 = new CustomButton.Button();
        txt_timKiemTenHang = new CustomTextField.TextField();
        btn_timKiem = new CustomButton.Button();
        jLabel1 = new javax.swing.JLabel();
        btn_xuatExcel = new CustomButton.Button();
        txt_makh = new javax.swing.JTextField();
        btn_reload = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        tbl_dsHD.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tbl_dsHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tbl_dsHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_dsHDMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_dsHD);

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setFocusCycleRoot(true);

        button4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-eye.gif"))); // NOI18N
        button4.setText("Xem chi tiết");
        button4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button4.setShadowColor(new java.awt.Color(204, 0, 153));
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });

        txt_timKiemTenHang.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txt_timKiemTenHang.setShadowColor(new java.awt.Color(255, 0, 255));
        txt_timKiemTenHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_timKiemTenHangActionPerformed(evt);
            }
        });

        btn_timKiem.setForeground(new java.awt.Color(255, 0, 0));
        btn_timKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-search.gif"))); // NOI18N
        btn_timKiem.setText("Tìm kiếm");
        btn_timKiem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_timKiem.setShadowColor(new java.awt.Color(51, 0, 204));
        btn_timKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timKiemActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setText("Số HĐ");

        btn_xuatExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-excel-48.png"))); // NOI18N
        btn_xuatExcel.setText("Excel");
        btn_xuatExcel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_xuatExcel.setShadowColor(new java.awt.Color(51, 0, 204));
        btn_xuatExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xuatExcelActionPerformed(evt);
            }
        });

        btn_reload.setBackground(new java.awt.Color(255, 255, 255));
        btn_reload.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_reload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-synchronize.gif"))); // NOI18N
        btn_reload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reloadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1)
                        .addGap(28, 28, 28)
                        .addComponent(txt_timKiemTenHang, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btn_timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(txt_makh, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(661, 661, 661)
                        .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(btn_xuatExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btn_reload)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(button4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_xuatExcel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_reload, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(2, 7, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_timKiemTenHang, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txt_makh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 43, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 153, 255));
        jLabel9.setText("Danh sách hóa đơn");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(670, 670, 670)
                .addComponent(jLabel9)
                .addContainerGap(719, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1004, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 139, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_timKiemTenHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_timKiemTenHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_timKiemTenHangActionPerformed

    private void btn_timKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timKiemActionPerformed
       if(txt_timKiemTenHang.getText().isEmpty()){
           JOptionPane.showMessageDialog(this,"Bạn chưa nhập thông tin hóa đơn cần tìm");
       }
       else
       {
           int t =Integer.parseInt(txt_timKiemTenHang.getText());
            ArrayList<HoaDon> dsHD = dsHDDAO.timHD(t);
            DefaultTableModel dtb = (DefaultTableModel)tbl_dsHD.getModel();
            dtb.setRowCount(0);
            for(HoaDon hd : dsHD)
            {
                Vector<Object> vec = new Vector<Object>();
                vec.add(hd.getMaHD());
                vec.add(hd.getTenNV());
                vec.add(hd.getNgayBan());
                vec.add(hd.getTongTien());
                vec.add(hd.getTenKH());
                dtb.addRow(vec);
            }
            tbl_dsHD.setModel(dtb);
            updateRowHeights();
       }
    }//GEN-LAST:event_btn_timKiemActionPerformed

    private void btn_xuatExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xuatExcelActionPerformed

        try {
            XSSFWorkbook workbook = new XSSFWorkbook();
            XSSFSheet spreadsheet = workbook.createSheet("DSHH");
            XSSFRow row = null;
            Cell cell = null;

            row = spreadsheet.createRow((short) 2);
            row.setHeight((short) 500);
            cell = row.createCell(0, CellType.STRING);
            cell.setCellValue("DANH SÁCH HÀNG HÓA");
            row = spreadsheet.createRow((short) 3);
            row.setHeight((short) 500);

            cell = row.createCell(0, CellType.STRING);
            cell.setCellValue("Mã HĐ ");
            cell = row.createCell(1, CellType.STRING);
            cell.setCellValue("Tên nhân viên");
            cell = row.createCell(2, CellType.STRING);
            cell.setCellValue("Ngày lập");
            cell = row.createCell(3, CellType.STRING);
            cell.setCellValue("Tổng tiền");
            cell = row.createCell(4, CellType.STRING);
            cell.setCellValue("Mã khách hàng");        
            ArrayList<HoaDon> dsHH = dsHDDAO.layDSHD();
            System.out.println(dsHH);
            for (int i = 0; i < dsHH.size(); i++) {
                HoaDon hh = dsHH.get(i);
                row = spreadsheet.createRow((short) 4 + i);
                row.setHeight((short) 400);
                row.createCell(0).setCellValue(hh.getMaHD());
                row.createCell(1).setCellValue(hh.getTenNV());
                row.createCell(2).setCellValue(hh.getNgayBan());
                row.createCell(3).setCellValue(hh.getTongTien());
                row.createCell(4).setCellValue(hh.getMaKH());
            }
            File  f = new File("D://danhsachHD.xlsx");
            try {
                FileOutputStream out = new FileOutputStream(f);
                workbook.write(out);
                out.close();
                JOptionPane.showMessageDialog(this, "Đã xuất file Excel");
                System.out.println("xuat thanh cong");
            } catch (FileNotFoundException ex) {
                ex.printStackTrace();
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_xuatExcelActionPerformed

    private void tbl_dsHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_dsHDMouseClicked
        int n = this.tbl_dsHD.getSelectedRow();
        this.txt_timKiemTenHang.setText(String.valueOf(tbl_dsHD.getValueAt(n, 0)));          
        this.txt_makh.setText(String.valueOf(tbl_dsHD.getValueAt(n, 4)));
    }//GEN-LAST:event_tbl_dsHDMouseClicked

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        String t="null";
        if(txt_makh.getText().trim().equals(t)){
               try {
               Hashtable map = new  Hashtable();
               JasperReport report  =  JasperCompileManager.compileReport("src/report/Hoadon_KhongKH.jrxml");
               int temp_maHD=Integer.parseInt(txt_timKiemTenHang.getText().trim());
               map.put("MAHD",temp_maHD);
               String strServer = "MSI\\SQLEXPRESS";
               String strDatabase = "QL_SIEUTHI_GG";
               String strUser = "sa";
               String strPass = "123";
               String connectURL = "jdbc:sqlserver://" + strServer
                                      + ":1433;databaseName=" + strDatabase
                                      + ";user =" + strUser + "; password= " + strPass;
               Connection conn;
               try {
                   conn = DriverManager.getConnection(connectURL);
                    JasperPrint jasperPrint = JasperFillManager.fillReport(report,map,conn);
                    JasperViewer.viewReport(jasperPrint,false);
               } catch (SQLException ex) {
                   Logger.getLogger(Form_LapHoaDon.class.getName()).log(Level.SEVERE, null, ex);
               }                       
           } catch (JRException ex) {
               Logger.getLogger(Form_LapHoaDon.class.getName()).log(Level.SEVERE, null, ex);
           }
        }
        else
        {
                try {
               Hashtable map = new  Hashtable();
               JasperReport report  =  JasperCompileManager.compileReport("src/report/Hoadon_CoKH.jrxml");
               int temp_maHD=Integer.parseInt(txt_timKiemTenHang.getText().trim());
               map.put("MAHD",temp_maHD);
               String strServer = "MSI\\SQLEXPRESS";
               String strDatabase = "QL_SIEUTHI_GG";
               String strUser = "sa";
               String strPass = "123";
               String connectURL = "jdbc:sqlserver://" + strServer
                                      + ":1433;databaseName=" + strDatabase
                                      + ";user =" + strUser + "; password= " + strPass;
               Connection conn;
               try {
                   conn = DriverManager.getConnection(connectURL);
                    JasperPrint jasperPrint = JasperFillManager.fillReport(report,map,conn);
                    JasperViewer.viewReport(jasperPrint,false);
               } catch (SQLException ex) {
                   Logger.getLogger(Form_LapHoaDon.class.getName()).log(Level.SEVERE, null, ex);
               }                       
           } catch (JRException ex) {
               Logger.getLogger(Form_LapHoaDon.class.getName()).log(Level.SEVERE, null, ex);
           }
        }
       
    }//GEN-LAST:event_button4ActionPerformed

    private void btn_reloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reloadActionPerformed
       hienThi();
       updateRowHeights();
    }//GEN-LAST:event_btn_reloadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_reload;
    private CustomButton.Button btn_timKiem;
    private CustomButton.Button btn_xuatExcel;
    private CustomButton.Button button4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_dsHD;
    private javax.swing.JTextField txt_makh;
    private CustomTextField.TextField txt_timKiemTenHang;
    // End of variables declaration//GEN-END:variables
}
