/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.raven.form;

import dao.ChucVuDAO;
import dao.NhanVienDAO;
import dao.TaiKhoanDAO;
import java.awt.Component;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jdbc.JDB_HienThi;
import pojo.ChucVu;
import pojo.NhanVien;
import pojo.TaiKhoan;

/**
 *
 * @author RAVEN
 */
public class Form_NhanVien extends javax.swing.JPanel {
   
    DefaultTableModel dtb = new DefaultTableModel();
    DefaultTableModel dtb_tk = new DefaultTableModel();
    String tieuDe_NV[] = {"Mã nhân viên", "Chức vụ", "Tên đăng nhập", "Tên nhân viên","Giới tính","Số điện thoại"};
    String tieuDe_TK[] = {"Tên đăng nhập", "Mật khẩu", "Tên nhân viên"};

    /**
     * Creates new form Form_1
     */
    public Form_NhanVien() {
        initComponents();
        dtb.setColumnIdentifiers(tieuDe_NV);
        dtb_tk.setColumnIdentifiers(tieuDe_TK);
        tbl_danhsach.setModel(dtb);
        tbl_danhsach_taikhoan.setModel(dtb_tk);
        HienThi_NV();
        HienThi_TK();
        HienThi_CBo_CV();
        chinhFont();
        updateRowHeights();
        updateRowHeights2();
        
        
    }
     public void chinhFont()
    {
        tbl_danhsach.getTableHeader().setFont(new Font("SansSerif", Font.BOLD, 20)); // chỉnh font chữ lại cho title
        tbl_danhsach.getTableHeader().setFont(new Font("SansSerif", Font.BOLD, 20));
          tbl_danhsach_taikhoan.getTableHeader().setFont(new Font("SansSerif", Font.BOLD, 20)); // chỉnh font chữ lại cho title
        tbl_danhsach_taikhoan.getTableHeader().setFont(new Font("SansSerif", Font.BOLD, 20));
    }
    private void updateRowHeights()
    {
        for (int row = 0; row < tbl_danhsach.getRowCount(); row++)
        {
            int rowHeight = tbl_danhsach.getRowHeight();

            for (int column = 0; column < tbl_danhsach.getColumnCount(); column++)
            {
                Component comp = tbl_danhsach.prepareRenderer(tbl_danhsach.getCellRenderer(row, column), row, column);
                rowHeight = Math.max(rowHeight, comp.getPreferredSize().height);
            }

            tbl_danhsach.setRowHeight(row, rowHeight);
        }              
    }
        private void updateRowHeights2()
    {
        for (int row = 0; row < tbl_danhsach_taikhoan.getRowCount(); row++)
        {
            int rowHeight = tbl_danhsach_taikhoan.getRowHeight();

            for (int column = 0; column < tbl_danhsach_taikhoan.getColumnCount(); column++)
            {
                Component comp = tbl_danhsach.prepareRenderer(tbl_danhsach_taikhoan.getCellRenderer(row, column), row, column);
                rowHeight = Math.max(rowHeight, comp.getPreferredSize().height);
            }

            tbl_danhsach_taikhoan.setRowHeight(row, rowHeight);
        }
              
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_tendn_nv = new CustomTextField.TextField();
        jLabel4 = new javax.swing.JLabel();
        txt_tennv = new CustomTextField.TextField();
        jLabel12 = new javax.swing.JLabel();
        cbo_cvu = new combobox.Combobox();
        txt_sdt = new CustomTextField.TextField();
        rbtn_nam = new javax.swing.JRadioButton();
        rbtn_nu = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_danhsach = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_mk = new CustomTextField.TextField();
        btn_them_tk = new CustomButton.Button();
        btn_xoa_tk = new CustomButton.Button();
        txt_tendn = new CustomTextField.TextField();
        btn_luu_tk = new CustomButton.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_danhsach_taikhoan = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        btn_them_nv = new CustomButton.Button();
        btn_luu_nv = new CustomButton.Button();
        btn_sua_nv = new CustomButton.Button();
        btn_xoa_nv = new CustomButton.Button();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 153, 255));
        jLabel8.setText("Quản Lý Nhân Viên");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(530, 530, 530)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(571, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(185, 209, 234));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 2));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 204));
        jLabel5.setText("Tên nhân viên");

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 204));
        jLabel6.setText("Tên đăng nhập");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 204));
        jLabel3.setText("Giới tính");

        txt_tendn_nv.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_tendn_nv.setShadowColor(new java.awt.Color(255, 0, 255));
        txt_tendn_nv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tendn_nvActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 204));
        jLabel4.setText("Chức vụ");

        txt_tennv.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_tennv.setShadowColor(new java.awt.Color(255, 0, 255));
        txt_tennv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tennvActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 204));
        jLabel12.setText("Số điện thoại");

        cbo_cvu.setEditable(true);
        cbo_cvu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nhà cung cấp 1", "Nhà cung cấp 2", "Nhà cung cấp 3", " " }));
        cbo_cvu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbo_cvu.setLabeText("");
        cbo_cvu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_cvuActionPerformed(evt);
            }
        });

        txt_sdt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_sdt.setShadowColor(new java.awt.Color(255, 0, 255));
        txt_sdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sdtActionPerformed(evt);
            }
        });

        rbtn_nam.setBackground(new java.awt.Color(185, 209, 234));
        buttonGroup1.add(rbtn_nam);
        rbtn_nam.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbtn_nam.setForeground(new java.awt.Color(0, 102, 204));
        rbtn_nam.setText("Nam");
        rbtn_nam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_namActionPerformed(evt);
            }
        });

        rbtn_nu.setBackground(new java.awt.Color(185, 209, 234));
        buttonGroup1.add(rbtn_nu);
        rbtn_nu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbtn_nu.setForeground(new java.awt.Color(0, 102, 204));
        rbtn_nu.setText("Nữ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_tendn_nv, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                            .addComponent(txt_tennv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtn_nam, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtn_nu, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(121, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cbo_cvu, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_tennv, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtn_nam)
                    .addComponent(rbtn_nu))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tendn_nv, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbo_cvu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        tbl_danhsach.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tbl_danhsach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_danhsach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_danhsachMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_danhsach);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(38, 176, 227));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 2));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tên đăng nhập");

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Mật khẩu");

        txt_mk.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_mk.setShadowColor(new java.awt.Color(255, 0, 255));
        txt_mk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_mkActionPerformed(evt);
            }
        });

        btn_them_tk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-plus.gif"))); // NOI18N
        btn_them_tk.setText("Thêm");
        btn_them_tk.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_them_tk.setShadowColor(new java.awt.Color(51, 0, 204));
        btn_them_tk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_them_tkActionPerformed(evt);
            }
        });

        btn_xoa_tk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-trash.gif"))); // NOI18N
        btn_xoa_tk.setText("Xóa");
        btn_xoa_tk.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_xoa_tk.setShadowColor(new java.awt.Color(51, 0, 204));
        btn_xoa_tk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoa_tkActionPerformed(evt);
            }
        });

        txt_tendn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_tendn.setShadowColor(new java.awt.Color(255, 0, 255));
        txt_tendn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tendnActionPerformed(evt);
            }
        });

        btn_luu_tk.setForeground(new java.awt.Color(255, 0, 0));
        btn_luu_tk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-save (1).gif"))); // NOI18N
        btn_luu_tk.setText("Lưu");
        btn_luu_tk.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_luu_tk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_luu_tkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_tendn, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                            .addComponent(txt_mk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btn_them_tk, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_luu_tk, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btn_xoa_tk, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tendn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_mk, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_them_tk, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_luu_tk, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_xoa_tk, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        tbl_danhsach_taikhoan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tbl_danhsach_taikhoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_danhsach_taikhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_danhsach_taikhoanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_danhsach_taikhoan);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btn_them_nv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-plus.gif"))); // NOI18N
        btn_them_nv.setText("Thêm");
        btn_them_nv.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_them_nv.setShadowColor(new java.awt.Color(51, 0, 204));
        btn_them_nv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_them_nvActionPerformed(evt);
            }
        });

        btn_luu_nv.setForeground(new java.awt.Color(255, 0, 0));
        btn_luu_nv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-save (1).gif"))); // NOI18N
        btn_luu_nv.setText("Lưu");
        btn_luu_nv.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_luu_nv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_luu_nvActionPerformed(evt);
            }
        });

        btn_sua_nv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-edit2.gif"))); // NOI18N
        btn_sua_nv.setText("Sửa");
        btn_sua_nv.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_sua_nv.setShadowColor(new java.awt.Color(0, 0, 204));
        btn_sua_nv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sua_nvActionPerformed(evt);
            }
        });

        btn_xoa_nv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-trash.gif"))); // NOI18N
        btn_xoa_nv.setText("Xóa");
        btn_xoa_nv.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_xoa_nv.setShadowColor(new java.awt.Color(51, 0, 204));
        btn_xoa_nv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoa_nvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(btn_them_nv, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_luu_nv, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btn_sua_nv, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btn_xoa_nv, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(843, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_them_nv, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_luu_nv, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_sua_nv, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_xoa_nv, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_tendn_nvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tendn_nvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tendn_nvActionPerformed

    private void txt_tennvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tennvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tennvActionPerformed

    private void cbo_cvuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_cvuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_cvuActionPerformed

    private void txt_sdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sdtActionPerformed

    private void txt_mkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_mkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mkActionPerformed

    private void txt_tendnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tendnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tendnActionPerformed

    private void btn_them_tkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_them_tkActionPerformed
        // TODO add your handling code here:
        txt_tendn.setText("");
        txt_mk.setText("");
        txt_tendn.requestFocus();
    }//GEN-LAST:event_btn_them_tkActionPerformed

    private void tbl_danhsach_taikhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_danhsach_taikhoanMouseClicked
        // TODO add your handling code here:
        int n = this.tbl_danhsach_taikhoan.getSelectedRow();
        this.txt_tendn.setText((String) tbl_danhsach_taikhoan.getValueAt(n, 0));
        this.txt_mk.setText((String) tbl_danhsach_taikhoan.getValueAt(n, 1));
        
        
    }//GEN-LAST:event_tbl_danhsach_taikhoanMouseClicked

    private void btn_luu_tkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_luu_tkActionPerformed
        // TODO add your handling code here:
        
        if (txt_tendn.getText().isEmpty() || txt_mk.getText().isEmpty())
        {
           JOptionPane.showMessageDialog(this, "Hãy nhập đủ thông tin!!!!");
           txt_tendn.requestFocus();
        }
        else
        {
           
            String tendn = txt_tendn.getText();
            String matkhau = txt_mk.getText();
            String maNV = "NULL";
            String quyen = "NULL";
            TaiKhoan tk = new TaiKhoan();
            tk.setTenDN(tendn);
            tk.setMatKhau(matkhau);
            //tk.setMaNV(Integer.parseInt(maNV));
            tk.setQuyen(quyen);
            if (TaiKhoanDAO.themTK(tk))
            {
                JOptionPane.showMessageDialog(this, "Thêm tài khoản thành công!!!");
                //HienThi_TK();
                HienThi_TK_chuacoNV();
                 updateRowHeights();
                 updateRowHeights2();
            }else
            {
                JOptionPane.showMessageDialog(this, "Tài khoản đã tồn tại !!!!");
            }
            
           
            
        }
           
    }//GEN-LAST:event_btn_luu_tkActionPerformed

    private void btn_xoa_tkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoa_tkActionPerformed
        // TODO add your handling code here:
        
        int row = tbl_danhsach_taikhoan.getSelectedRow();
        if (row == -1)
        {
            JOptionPane.showMessageDialog(this, "Hãy chọn dòng cần xóa ");
            return;
        }
        else 
        {
            int n = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa?", "Thông báo", JOptionPane.NO_OPTION);
            if (n == JOptionPane.NO_OPTION)
            {
                return;
            }
            else
            {
                String tendn = txt_tendn.getText();
                if (TaiKhoanDAO.xoaTK(tendn))
                {
                    JOptionPane.showMessageDialog(this, "Xóa thành công");
                    HienThi_TK();
                     updateRowHeights();
                    updateRowHeights2();
                }
                else 
                {
                    JOptionPane.showMessageDialog(this, "Tài khoản thuộc sở hữu của nhân viên");
                }
               
               
            }
            
        }
        
 
    }//GEN-LAST:event_btn_xoa_tkActionPerformed

    private void tbl_danhsachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_danhsachMouseClicked
        // TODO add your handling code here:
        int n = this.tbl_danhsach.getSelectedRow();
        this.txt_tennv.setText((String) tbl_danhsach.getValueAt(n, 3));
        this.txt_tendn_nv.setText((String) tbl_danhsach.getValueAt(n, 2));
        this.cbo_cvu.setSelectedItem((String) tbl_danhsach.getValueAt(n, 1));
        String rbtn = (String) tbl_danhsach.getValueAt(n, 4);
        if (rbtn.equals("Nữ"))
        {
            this.rbtn_nu.setSelected(true);
        }
        else
        {
            this.rbtn_nam.setSelected(true);
        }
        this.txt_sdt.setText((String) tbl_danhsach.getValueAt(n, 5));
        
    }//GEN-LAST:event_tbl_danhsachMouseClicked

    private void rbtn_namActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_namActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_namActionPerformed

    private void btn_them_nvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_them_nvActionPerformed
        // TODO add your handling code here:
        this.txt_tennv.setText("");
        this.txt_tennv.requestFocus();
        this.txt_tendn_nv.setText("");
        this.cbo_cvu.setSelectedIndex(0);
        this.buttonGroup1.clearSelection();
        this.txt_sdt.setText("");
        
    }//GEN-LAST:event_btn_them_nvActionPerformed

    private void btn_luu_nvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_luu_nvActionPerformed
        // TODO add your handling code here:
       if (txt_tennv.getText().isEmpty() || txt_tendn_nv.getText().isEmpty() || txt_sdt.getText().isEmpty())
       {
           JOptionPane.showMessageDialog(this, "Hãy nhập đủ thông tin");
           
       }
       if (NhanVienDAO.KT_tenDN(txt_tendn_nv.getText().trim()))
       {
           JOptionPane.showMessageDialog(this, "tên đăng nhập đã tồn lại!!!");
           txt_tendn_nv.requestFocus();
       }
       else
       {
            int macv = cbo_cvu.getSelectedIndex();
            String tendn = txt_tendn_nv.getText();
            String tennv = txt_tennv.getText();
            String gtinh= "";
             if (rbtn_nu.equals("Nữ"))
             {
                 gtinh = "Nữ";
             }
             else
             {
                 gtinh = "Nam";
             }
            String sdt = txt_sdt.getText();  
            macv++; //index table = 0;

            NhanVien nv = new NhanVien();
            nv.setMaCV(macv);
            nv.setTenDN(tendn);
            nv.setTenNV(tennv);
            nv.setgTinh(gtinh);
            nv.setSdt(sdt);
            if (NhanVienDAO.themNV(nv))
            { 
                JOptionPane.showMessageDialog(this, "Thêm nhân viên thành công!!!");
                HienThi_NV();
                HienThi_TK();
                 updateRowHeights();
                updateRowHeights2();
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Thêm nhân viên thất bại!!!");
            }
            
       }
       
        
//       
       
    }//GEN-LAST:event_btn_luu_nvActionPerformed

    private void btn_xoa_nvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoa_nvActionPerformed
        // TODO add your handling code here:
        
        int row = tbl_danhsach.getSelectedRow();
        if (row == -1)
        {
            JOptionPane.showMessageDialog(this, "Hãy chọn dòng cần xóa");
            return;
        }
        else 
        {
            int n = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa?", "Thông báo", JOptionPane.NO_OPTION);
            if (n == JOptionPane.NO_OPTION)
            {
                return;
            }
            else
            {   
                String manv = (String.valueOf(tbl_danhsach.getValueAt(row, 0)));
                int ma = Integer.parseInt(manv);
                if (NhanVienDAO.xoaNV(ma))
                {
                    JOptionPane.showMessageDialog(this, "Xóa thành công");
                    HienThi_NV();
                    HienThi_TK();
                    updateRowHeights();
                    updateRowHeights2();
                }
                else 
                {
                    JOptionPane.showMessageDialog(this, "Tài khoản thuộc sở hữu của nhân viên");
                }
               
               
            }
            
        }
        
    }//GEN-LAST:event_btn_xoa_nvActionPerformed

    private void btn_sua_nvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sua_nvActionPerformed
        // TODO add your handling code here:
       int row = tbl_danhsach.getSelectedRow();
        if (row == -1)
        {
            JOptionPane.showMessageDialog(this, "Hãy chọn dòng cần sửa");
            return;
        }
        else 
        {
                
            String manv = (String.valueOf(tbl_danhsach.getValueAt(row, 0)));
            int macv = cbo_cvu.getSelectedIndex();
            String tendn = txt_tendn_nv.getText();
            String tennv = txt_tennv.getText();
            String gtinh= "";
             if (rbtn_nu.isSelected())
             {
                 gtinh = "Nữ";
             }
             else
             {
                 gtinh = "Nam";
             }
            String sdt = txt_sdt.getText();  
            macv++; //index table = 0;
                NhanVien nv = new NhanVien();
                nv.setMaCV(macv);
                nv.setTenDN(tendn);
                nv.setTenNV(tennv);
                nv.setgTinh(gtinh);
                nv.setSdt(sdt);
                nv.setMaNV(Integer.parseInt(manv));
                if (NhanVienDAO.suaNV(nv))
                {
                    JOptionPane.showMessageDialog(this, "sửa thành công");
                    HienThi_NV();
                    
                    updateRowHeights();
                    updateRowHeights2();
                }
                else 
                {
                    JOptionPane.showMessageDialog(this, "sửa thất bại");
                }
                
               
               
           
            
        }
        
    }//GEN-LAST:event_btn_sua_nvActionPerformed
    
    private boolean KT_TenDN(String tendn)
    {
     
//        String sql = "select * from TaiKhoan where TENDN='"+ tendn.trim() +"'";
//        try {
//            resultSet = statement.executeQuery(sql);
//            if (resultSet.next())
//            {
//                return true;
//            }
//            else
//            {
//                return false;
//            }
//        } catch (SQLException ex) {
//            Logger.getLogger(Form_NhanVien.class.getName()).log(Level.SEVERE, null, ex);
//        }
        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private CustomButton.Button btn_luu_nv;
    private CustomButton.Button btn_luu_tk;
    private CustomButton.Button btn_sua_nv;
    private CustomButton.Button btn_them_nv;
    private CustomButton.Button btn_them_tk;
    private CustomButton.Button btn_xoa_nv;
    private CustomButton.Button btn_xoa_tk;
    private javax.swing.ButtonGroup buttonGroup1;
    private combobox.Combobox cbo_cvu;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton rbtn_nam;
    private javax.swing.JRadioButton rbtn_nu;
    private javax.swing.JTable tbl_danhsach;
    private javax.swing.JTable tbl_danhsach_taikhoan;
    private CustomTextField.TextField txt_mk;
    private CustomTextField.TextField txt_sdt;
    private CustomTextField.TextField txt_tendn;
    private CustomTextField.TextField txt_tendn_nv;
    private CustomTextField.TextField txt_tennv;
    // End of variables declaration//GEN-END:variables


    


    private void HienThi_NV() {
        ArrayList<NhanVien> dsNV = NhanVienDAO.layDSNhanVien();
        DefaultTableModel dtb = (DefaultTableModel)tbl_danhsach.getModel();
        dtb.setRowCount(0);
        for(NhanVien nv : dsNV)
        {
            Vector<Object> vec = new Vector<Object>();
            vec.add(nv.getMaNV());
            vec.add(nv.getTenCV());
            vec.add(nv.getTenDN());
            vec.add(nv.getTenNV());
            vec.add(nv.getgTinh());
            vec.add(nv.getSdt());
           
            dtb.addRow(vec);
        }
        tbl_danhsach.setModel(dtb);
        
        
        
    }



    private void HienThi_CBo_CV() {

        ArrayList<ChucVu> dsCV = ChucVuDAO.layDSChucVu();
        DefaultTableModel tbmode = (DefaultTableModel) tbl_danhsach_taikhoan.getModel();
        DefaultComboBoxModel cbomode = (DefaultComboBoxModel) cbo_cvu.getModel();
        cbo_cvu.removeAllItems(); // xóa hết dl trong cbo
        for(ChucVu cv : dsCV)
        {   
            cbomode.addElement(cv.getTenCV());

        }
        

    }

    

    private void HienThi_TK() {
        ArrayList<TaiKhoan> dsTK = TaiKhoanDAO.layDSTaiKhoan();
        DefaultTableModel dtb = (DefaultTableModel)tbl_danhsach_taikhoan.getModel();
        dtb.setRowCount(0);
        for(TaiKhoan tk : dsTK)
        {
            Vector<Object> vec = new Vector<Object>();
            vec.add(tk.getTenDN());
            vec.add(tk.getMatKhau());
            vec.add(tk.getTenNV());
           
           
            dtb.addRow(vec);
        }
        tbl_danhsach_taikhoan.setModel(dtb);
        
    }
  
    private void HienThi_TK_chuacoNV() {
        DefaultTableModel dtb = (DefaultTableModel)tbl_danhsach_taikhoan.getModel();
      
        Vector<Object> vec = new Vector<Object>();
        vec.add(txt_tendn.getText());
        vec.add(txt_mk.getText());
        vec.add("");

        dtb.addRow(vec);
        tbl_danhsach_taikhoan.setModel(dtb);
    }

   
}
